### ISSUE TITLE
Bulk import in .csv?

### ISSUE THREAD

**Issue by nefirma** [vsimakhin/web-logbook#20]
Subject?

**Comment by vsimakhin** [comment]
Well, since the backend is based on sqlite which is created locally in the same location with binary, it's **_easy-ish_** to import csv knowing the right table structure (https://github.com/vsimakhin/web-logbook/blob/main/internal/driver/db.structure)

https://www.sqlitetutorial.net/sqlite-import-csv/

But yep, the csv should be prepared first. I think I need to write at least some readme for that
